main: online.vitreusmc.vitreusTweaks.VitreusTweaks

name: VitreusTweaks
version: 0.0.1
description:  A Bukkit plugin created for the Vitreus Minecraft community that adds simple, vanilla-like features.
permissions:
  module.gags:
    description: Allows the execution of gag commands.
    default: false

commands:
  armorstand:
    description: Allows you to manipulate nearby armorstands.
    usage: /mas
    aliases: [as, mas, manipulate_armor_stand]
    permission: milestone.24
  sleepy:
    description: Announce your sleepiness and help throw the sun up into the sky!
    usage: /sleepy
    aliases: [ok, sleep]
  pickup:
    description: Picksup a nearby entity!
    usage: /pickup
    permission: module.gags
  map:
    description: Broadcast your coordinates and a link to your location on the online map!
    usage: /map
    aliases: [coordinates, coords]
  compass:
    description: Set your compass' coordinates!
    usage: /compass <here|bed|spawn> || <x> <y> <z>
    aliases: [setcompass]
